### ISSUE TITLE
Need fix problem.

### ISSUE THREAD

**Issue by Creater3d** [uujuju1/project-oblivion#17]
[crash-report-05_29_2022_16_38_19.txt](https://github.com/uujuju1/project-oblivion/files/8793432/crash-report-05_29_2022_16_38_19.txt)

**Comment by uujuju1** [comment]
the mod works fine in my phone
did it crash on startup or were you doing something else?
if you made it crash using something in the mod please tell how you made it
and another question
did you use the actions build or the releases build?

**Comment by Creater3d** [comment]
Good day, you have discord account?

пн, 30 мая 2022 г. в 03:58, uujuju ***@***.***>:

**Comment by Creater3d** [comment]
![image](https://user-images.githubusercontent.com/73776761/170926255-0a7e3975-d863-46d6-a95e-6297d29c4d89.png)

![image](https://user-images.githubusercontent.com/73776761/170926340-e5a069e3-9dd5-470e-aa5c-db42ddca4c23.png)

It is crash when i open Oldtown map.

**Comment by uujuju1** [comment]
i have a discord server for the mod
im gonna put the link in readme.md soon

and
_**idk how to fix this thing lmao**_

**Comment by uujuju1** [comment]
ah i see
map is corrupted
i have to remake it
soon the map will be available i think

**Comment by Creater3d** [comment]
Glad to hear that))

пн, 30 мая 2022 г. в 18:58, uujuju ***@***.***>:

**Comment by Creater3d** [comment]
When you fix?

**Comment by uujuju1** [comment]
i may have forgotten to add the new map into the techtree
