### ISSUE TITLE
Mercuire Corrupting save files

### ISSUE THREAD

**Issue by PadSmid** [uujuju1/project-oblivion#20]
Steps to reproduce
1. Make a new save
2. Spawn Mercuire
3. And now your save has been corrupted forever!

**Comment by uujuju1** [comment]
the problem occurs with every copter
not just mercurie
but i dont even know why it happens

**Comment by uujuju1** [comment]
maybe it has something to do with the CopterComp
but i dont know a good way to fix it without removing the rotor blurring mechanic
for now use the other units as im making some side projects by now
if you create a copter by accident remove it using the console
just enable the console and put Vars.player.unit().kill() when controlling said copter

**Comment by PadSmid** [comment]
Thanks!
