### ISSUE TITLE
Not being able to launch to a new sector on Lamoni

### ISSUE THREAD

**Issue by Mac33299** [uujuju1/project-oblivion#22]
Since you start on the first sector with 'Core: Shard' and because Core Village and Shard are both 3x3 there is no way to replace Shard with Village thus no way to launch to other sector

(unrelated: Niobium conduits bridge soft locks  any sectors it's placed in)

**Comment by uujuju1** [comment]
wont fix since im not working on this mod anymore

im working on a new mod called monolith(can only be downloaded through actions)
